title: CR-DBS at home
description: At-home assessment instructions for the CR-DBS study
theme: just-the-docs

url: https://petermgrund.github.io/cr-dbs-at-home/

aux_links:
  Template Repository: https://github.com/petermgrund/cr-dbs-at-home
